# Generated by Django 5.0.2 on 2024-03-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='producto',
            field=models.CharField(max_length=100),
        ),
    ]
