# Generated by Django 5.0.2 on 2024-03-11 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_proveedor_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='documento',
            new_name='cuit',
        ),
    ]
